#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEditor.Events;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using SurvivalGame.CameraSystem;
using SurvivalGame.Character;
using SurvivalGame.Inventory;
using SurvivalGame.Player;
using SurvivalGame.UI;
using SurvivalGame.World;

namespace SurvivalGame.EditorTools
{
    [InitializeOnLoad]
    public static class PrototypeAutoBuilder
    {
        private const string GeneratedFolder = "Assets/Generated";
        private const string ScenesFolder = "Assets/Scenes";
        private const string Marker = GeneratedFolder + "/Prototype_v1.marker";

        static PrototypeAutoBuilder()
        {
            EditorApplication.delayCall += AutoBuildIfNeeded;
        }

        [MenuItem("Survival Game/Rebuild Playable Prototype")]
        public static void RebuildFromMenu()
        {
            BuildAll();
        }

        private static void AutoBuildIfNeeded()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling || File.Exists(Marker))
                return;

            BuildAll();
        }

        private static void BuildAll()
        {
            EnsureFolder("Assets", "Generated");
            EnsureFolder("Assets", "Scenes");

            BuildCharacterCreator();
            BuildWorldMap();
            BuildLocation("HomeBase", false);
            BuildLocation("ForestLocation", true);

            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(ScenesFolder + "/CharacterCreator.unity", true),
                new EditorBuildSettingsScene(ScenesFolder + "/WorldMap.unity", true),
                new EditorBuildSettingsScene(ScenesFolder + "/HomeBase.unity", true),
                new EditorBuildSettingsScene(ScenesFolder + "/ForestLocation.unity", true)
            };

            File.WriteAllText(Marker,
                "Generated by PrototypeAutoBuilder. Delete this file or use Survival Game > Rebuild Playable Prototype to rebuild.");
            AssetDatabase.Refresh();
            AssetDatabase.SaveAssets();

            EditorSceneManager.OpenScene(ScenesFolder + "/CharacterCreator.unity");
            Debug.Log("Survival Game prototype scenes generated successfully.");
        }

        private static void BuildCharacterCreator()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            CreateWorldLighting();

            var camera = new GameObject("Main Camera").AddComponent<Camera>();
            camera.tag = "MainCamera";
            camera.transform.position = new Vector3(0f, 1.7f, -5.2f);
            camera.transform.rotation = Quaternion.Euler(8f, 0f, 0f);
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.055f, 0.07f, 0.075f);

            var floor = GameObject.CreatePrimitive(PrimitiveType.Plane);
            floor.name = "Creator Floor";
            floor.transform.localScale = new Vector3(0.7f, 1f, 0.7f);

            var model = GameObject.CreatePrimitive(PrimitiveType.Capsule);
            model.name = "Character Preview Placeholder";
            model.transform.position = new Vector3(0f, 1f, 0f);
            model.GetComponent<Renderer>().sharedMaterial = CreateColorMaterial(
                "PrototypeCharacter", new Color(0.32f, 0.36f, 0.36f));

            var canvas = CreateCanvas("Character Creator UI");
            var controllerGo = new GameObject("CharacterCreatorController");
            var controller = controllerGo.AddComponent<CharacterCreatorController>();

            CreateText(canvas.transform, "Title", "СОЗДАНИЕ ПЕРСОНАЖА",
                new Vector2(0.06f, 0.90f), new Vector2(0.48f, 0.98f), 34, TextAnchor.MiddleLeft);

            var nickname = CreateInputField(canvas.transform, "Nickname", "Никнейм",
                new Vector2(0.06f, 0.77f), new Vector2(0.35f, 0.84f));

            var summary = CreateText(canvas.transform, "Summary", "",
                new Vector2(0.06f, 0.42f), new Vector2(0.32f, 0.72f), 24, TextAnchor.UpperLeft);

            BindObject(controller, "nicknameInput", nickname);
            BindObject(controller, "summaryText", summary);

            CreateMethodButton(canvas.transform, "Male", "МУЖЧИНА",
                new Vector2(0.06f, 0.67f), new Vector2(0.19f, 0.73f), controller.SetMale);
            CreateMethodButton(canvas.transform, "Female", "ЖЕНЩИНА",
                new Vector2(0.20f, 0.67f), new Vector2(0.34f, 0.73f), controller.SetFemale);
            CreateMethodButton(canvas.transform, "Skin", "ЦВЕТ КОЖИ",
                new Vector2(0.06f, 0.33f), new Vector2(0.22f, 0.39f), controller.NextSkin);
            CreateMethodButton(canvas.transform, "Hair", "ПРИЧЁСКА",
                new Vector2(0.06f, 0.25f), new Vector2(0.22f, 0.31f), controller.NextHair);
            CreateMethodButton(canvas.transform, "HairColor", "ЦВЕТ ВОЛОС",
                new Vector2(0.06f, 0.17f), new Vector2(0.22f, 0.23f), controller.NextHairColor);
            CreateMethodButton(canvas.transform, "Beard", "БОРОДА",
                new Vector2(0.06f, 0.09f), new Vector2(0.22f, 0.15f), controller.ToggleBeard);
            CreateMethodButton(canvas.transform, "Create", "СОЗДАТЬ ПЕРСОНАЖА",
                new Vector2(0.70f, 0.08f), new Vector2(0.94f, 0.16f), controller.CreateCharacter);

            EditorSceneManager.SaveScene(scene, ScenesFolder + "/CharacterCreator.unity");
        }

        private static void BuildWorldMap()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var camera = new GameObject("Main Camera").AddComponent<Camera>();
            camera.tag = "MainCamera";
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.035f, 0.055f, 0.045f);

            var canvas = CreateCanvas("World Map UI");
            CreatePanel(canvas.transform, "Map Background",
                new Vector2(0f, 0f), new Vector2(1f, 1f),
                new Color(0.07f, 0.10f, 0.075f, 1f));

            CreateText(canvas.transform, "Title", "КАРТА МИРА",
                new Vector2(0.04f, 0.90f), new Vector2(0.40f, 0.98f), 38, TextAnchor.MiddleLeft);

            CreateTravelButton(canvas.transform, "HomeBase", "ДОМ",
                new Vector2(0.20f, 0.46f), new Vector2(0.34f, 0.58f), "HomeBase");

            CreateTravelButton(canvas.transform, "Forest", "ЛЕС",
                new Vector2(0.60f, 0.52f), new Vector2(0.74f, 0.64f), "ForestLocation");

            CreateText(canvas.transform, "Hint",
                "Прототип карты: позже здесь будут реальные точки, энергия, события и маршруты.",
                new Vector2(0.22f, 0.10f), new Vector2(0.78f, 0.18f), 22, TextAnchor.MiddleCenter);

            EditorSceneManager.SaveScene(scene, ScenesFolder + "/WorldMap.unity");
        }

        private static void BuildLocation(string sceneName, bool forest)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            CreateWorldLighting();

            var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = forest ? "Forest Ground" : "Home Ground";
            ground.transform.localScale = new Vector3(6f, 1f, 6f);
            ground.GetComponent<Renderer>().sharedMaterial = CreateColorMaterial(
                sceneName + "_Ground",
                forest ? new Color(0.17f, 0.25f, 0.14f) : new Color(0.27f, 0.24f, 0.18f));

            if (forest)
                CreateForestProps();
            else
                CreateHomeProps();

            var player = CreatePrototypePlayer();

            var cameraGo = new GameObject("Main Camera");
            var camera = cameraGo.AddComponent<Camera>();
            camera.tag = "MainCamera";
            cameraGo.AddComponent<IsometricCameraFollow>().Bind(player.transform);
            camera.fieldOfView = 48f;

            var loaderGo = new GameObject("LocationLoader");
            var loader = loaderGo.AddComponent<LocationLoader>();

            CreateExitZone(new Vector3(0f, 0.5f, 28f), new Vector3(20f, 1f, 4f), loader);
            CreateExitZone(new Vector3(0f, 0.5f, -28f), new Vector3(20f, 1f, 4f), loader);
            CreateExitZone(new Vector3(28f, 0.5f, 0f), new Vector3(4f, 1f, 20f), loader);
            CreateExitZone(new Vector3(-28f, 0.5f, 0f), new Vector3(4f, 1f, 20f), loader);

            CreateGameplayHud(player);

            EditorSceneManager.SaveScene(scene, ScenesFolder + "/" + sceneName + ".unity");
        }

        private static GameObject CreatePrototypePlayer()
        {
            var player = GameObject.CreatePrimitive(PrimitiveType.Capsule);
            player.name = "Player";
            player.tag = "Player";
            player.transform.position = new Vector3(0f, 1f, 0f);

            Object.DestroyImmediate(player.GetComponent<CapsuleCollider>());
            var cc = player.AddComponent<CharacterController>();
            cc.height = 2f;
            cc.radius = 0.42f;
            cc.center = new Vector3(0f, 0f, 0f);

            player.AddComponent<MobileRunController>();
            player.AddComponent<PlayerVitals>();
            player.AddComponent<PlayerProgression>();
            player.AddComponent<InventoryContainer>();

            player.GetComponent<Renderer>().sharedMaterial =
                CreateColorMaterial("PrototypePlayer", new Color(0.30f, 0.34f, 0.35f));

            return player;
        }

        private static void CreateGameplayHud(GameObject player)
        {
            var canvas = CreateCanvas("Gameplay HUD");

            var topPanel = CreatePanel(canvas.transform, "Player HUD",
                new Vector2(0.02f, 0.79f), new Vector2(0.31f, 0.98f),
                new Color(0.025f, 0.035f, 0.04f, 0.82f));

            var nickname = CreateText(topPanel.transform, "Nickname", "Player",
                new Vector2(0.12f, 0.72f), new Vector2(0.62f, 0.96f), 24, TextAnchor.MiddleLeft);
            var level = CreateText(topPanel.transform, "Level", "1",
                new Vector2(0.75f, 0.72f), new Vector2(0.94f, 0.96f), 22, TextAnchor.MiddleCenter);

            var healthBar = CreateSlider(topPanel.transform, "Health",
                new Vector2(0.12f, 0.46f), new Vector2(0.65f, 0.64f));
            var healthText = CreateText(topPanel.transform, "HealthText", "100 / 100",
                new Vector2(0.67f, 0.44f), new Vector2(0.96f, 0.66f), 18, TextAnchor.MiddleCenter);

            var armorBar = CreateSlider(topPanel.transform, "Armor",
                new Vector2(0.12f, 0.24f), new Vector2(0.65f, 0.40f));
            var armorText = CreateText(topPanel.transform, "ArmorText", "0 / 100",
                new Vector2(0.67f, 0.20f), new Vector2(0.96f, 0.42f), 18, TextAnchor.MiddleCenter);

            var foodText = CreateText(topPanel.transform, "Food", "🍖 100",
                new Vector2(0.12f, 0.02f), new Vector2(0.42f, 0.20f), 19, TextAnchor.MiddleLeft);
            var waterText = CreateText(topPanel.transform, "Water", "💧 100",
                new Vector2(0.50f, 0.02f), new Vector2(0.82f, 0.20f), 19, TextAnchor.MiddleLeft);

            var expBar = CreateSlider(canvas.transform, "EXP",
                new Vector2(0.38f, 0.018f), new Vector2(0.62f, 0.032f));
            var bottomLevel = CreateText(canvas.transform, "BottomLevel", "Ур. 1",
                new Vector2(0.31f, 0.006f), new Vector2(0.38f, 0.048f), 16, TextAnchor.MiddleRight);
            var expText = CreateText(canvas.transform, "EXPText", "0 / 100",
                new Vector2(0.62f, 0.006f), new Vector2(0.70f, 0.048f), 16, TextAnchor.MiddleLeft);

            var joystickBg = CreatePanel(canvas.transform, "Joystick",
                new Vector2(0.035f, 0.055f), new Vector2(0.17f, 0.29f),
                new Color(0.08f, 0.09f, 0.10f, 0.55f));
            joystickBg.GetComponent<Image>().raycastTarget = true;
            var handle = CreatePanel(joystickBg.transform, "Handle",
                new Vector2(0.30f, 0.30f), new Vector2(0.70f, 0.70f),
                new Color(0.65f, 0.68f, 0.70f, 0.78f));

            var joystick = joystickBg.AddComponent<VirtualJoystick>();
            joystick.Bind(player.GetComponent<MobileRunController>());
            BindObject(joystick, "background", joystickBg.transform as RectTransform);
            BindObject(joystick, "handle", handle.transform as RectTransform);

            var presenter = canvas.gameObject.AddComponent<PlayerHudPresenter>();
            BindObject(presenter, "vitals", player.GetComponent<PlayerVitals>());
            BindObject(presenter, "progression", player.GetComponent<PlayerProgression>());
            BindObject(presenter, "nicknameText", nickname);
            BindObject(presenter, "levelText", level);
            BindObject(presenter, "healthBar", healthBar);
            BindObject(presenter, "healthText", healthText);
            BindObject(presenter, "armorBar", armorBar);
            BindObject(presenter, "armorText", armorText);
            BindObject(presenter, "foodText", foodText);
            BindObject(presenter, "waterText", waterText);
            BindObject(presenter, "expBar", expBar);
            BindObject(presenter, "bottomLevelText", bottomLevel);
            BindObject(presenter, "expText", expText);

            CreateText(canvas.transform, "PrototypeNote",
                "ПРОТОТИП • финальный HUD будет заменён утверждённым артом",
                new Vector2(0.72f, 0.94f), new Vector2(0.98f, 0.985f), 13, TextAnchor.MiddleRight);
        }

        private static void CreateExitZone(Vector3 position, Vector3 scale, LocationLoader loader)
        {
            var zone = GameObject.CreatePrimitive(PrimitiveType.Cube);
            zone.name = "ExitZone";
            zone.transform.position = position;
            zone.transform.localScale = scale;

            var renderer = zone.GetComponent<Renderer>();
            renderer.sharedMaterial = CreateColorMaterial(
                "ExitZoneGreen", new Color(0.10f, 0.85f, 0.25f, 0.30f));

            var collider = zone.GetComponent<BoxCollider>();
            collider.isTrigger = true;

            var exit = zone.AddComponent<ExitZone>();
            BindObject(exit, "loader", loader);
            BindString(exit, "worldMapScene", "WorldMap");
        }

        private static void CreateForestProps()
        {
            for (int i = 0; i < 18; i++)
            {
                float angle = i * Mathf.PI * 2f / 18f;
                float radius = 13f + (i % 4) * 2.5f;
                var tree = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                tree.name = "Tree Placeholder";
                tree.transform.position = new Vector3(Mathf.Cos(angle) * radius, 1.5f, Mathf.Sin(angle) * radius);
                tree.transform.localScale = new Vector3(0.55f, 1.5f, 0.55f);
                tree.GetComponent<Renderer>().sharedMaterial =
                    CreateColorMaterial("TreePlaceholder", new Color(0.22f, 0.16f, 0.08f));
            }

            for (int i = 0; i < 10; i++)
            {
                var rock = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                rock.name = "Stone Placeholder";
                rock.transform.position = new Vector3(-10f + i * 2.2f, 0.45f, 7f + (i % 3) * 2f);
                rock.transform.localScale = new Vector3(1.0f, 0.6f, 0.8f);
                rock.GetComponent<Renderer>().sharedMaterial =
                    CreateColorMaterial("RockPlaceholder", new Color(0.34f, 0.35f, 0.34f));
            }
        }

        private static void CreateHomeProps()
        {
            var shack = GameObject.CreatePrimitive(PrimitiveType.Cube);
            shack.name = "Starter Shelter Placeholder";
            shack.transform.position = new Vector3(8f, 1.5f, 5f);
            shack.transform.localScale = new Vector3(5f, 3f, 4f);
            shack.GetComponent<Renderer>().sharedMaterial =
                CreateColorMaterial("ShelterPlaceholder", new Color(0.29f, 0.22f, 0.14f));

            var fire = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            fire.name = "Campfire Placeholder";
            fire.transform.position = new Vector3(3f, 0.2f, -2f);
            fire.transform.localScale = new Vector3(1.1f, 0.2f, 1.1f);
            fire.GetComponent<Renderer>().sharedMaterial =
                CreateColorMaterial("FirePlaceholder", new Color(0.90f, 0.34f, 0.08f));
        }

        private static Canvas CreateCanvas(string name)
        {
            var go = new GameObject(name);
            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = go.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.matchWidthOrHeight = 0.5f;

            go.AddComponent<GraphicRaycaster>();

            if (!Object.FindFirstObjectByType<EventSystem>())
            {
                var es = new GameObject("EventSystem");
                es.AddComponent<EventSystem>();
                es.AddComponent<InputSystemUIInputModule>();
            }

            return canvas;
        }

        private static GameObject CreatePanel(Transform parent, string name, Vector2 min, Vector2 max, Color color)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Image));
            go.transform.SetParent(parent, false);
            SetAnchors(go.GetComponent<RectTransform>(), min, max);
            go.GetComponent<Image>().color = color;
            return go;
        }

        private static Text CreateText(Transform parent, string name, string value,
            Vector2 min, Vector2 max, int size, TextAnchor anchor)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Text));
            go.transform.SetParent(parent, false);
            SetAnchors(go.GetComponent<RectTransform>(), min, max);

            var text = go.GetComponent<Text>();
            text.text = value;
            text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            text.fontSize = size;
            text.alignment = anchor;
            text.color = Color.white;
            text.supportRichText = true;
            text.resizeTextForBestFit = false;
            return text;
        }

        private static InputField CreateInputField(Transform parent, string name, string placeholder,
            Vector2 min, Vector2 max)
        {
            var bg = CreatePanel(parent, name, min, max, new Color(0.08f, 0.10f, 0.11f, 0.94f));
            var input = bg.AddComponent<InputField>();

            var text = CreateText(bg.transform, "Text", "", new Vector2(0.04f, 0.10f), new Vector2(0.96f, 0.90f), 22, TextAnchor.MiddleLeft);
            var hint = CreateText(bg.transform, "Placeholder", placeholder, new Vector2(0.04f, 0.10f), new Vector2(0.96f, 0.90f), 22, TextAnchor.MiddleLeft);
            hint.color = new Color(1f, 1f, 1f, 0.35f);

            input.textComponent = text;
            input.placeholder = hint;
            return input;
        }

        private static Button CreateMethodButton(Transform parent, string name, string label,
            Vector2 min, Vector2 max, UnityEngine.Events.UnityAction action)
        {
            var button = CreateButton(parent, name, label, min, max);
            UnityEventTools.AddPersistentListener(button.onClick, action);
            return button;
        }

        private static void CreateTravelButton(Transform parent, string name, string label,
            Vector2 min, Vector2 max, string sceneName)
        {
            var button = CreateButton(parent, name, label, min, max);
            var travel = button.gameObject.AddComponent<SceneTravelButton>();
            travel.SetScene(sceneName);
            UnityEventTools.AddPersistentListener(button.onClick, travel.Travel);
        }

        private static Button CreateButton(Transform parent, string name, string label, Vector2 min, Vector2 max)
        {
            var go = CreatePanel(parent, name, min, max, new Color(0.13f, 0.22f, 0.23f, 0.95f));
            var button = go.AddComponent<Button>();
            button.targetGraphic = go.GetComponent<Image>();
            CreateText(go.transform, "Label", label, new Vector2(0f, 0f), new Vector2(1f, 1f), 22, TextAnchor.MiddleCenter);
            return button;
        }

        private static Slider CreateSlider(Transform parent, string name, Vector2 min, Vector2 max)
        {
            var root = new GameObject(name, typeof(RectTransform), typeof(Slider));
            root.transform.SetParent(parent, false);
            SetAnchors(root.GetComponent<RectTransform>(), min, max);

            var bg = CreatePanel(root.transform, "Background", Vector2.zero, Vector2.one, new Color(0.04f, 0.05f, 0.055f, 0.95f));
            var fill = CreatePanel(root.transform, "Fill", new Vector2(0f, 0f), new Vector2(1f, 1f), new Color(0.20f, 0.66f, 0.70f, 1f));

            var slider = root.GetComponent<Slider>();
            slider.fillRect = fill.GetComponent<RectTransform>();
            slider.targetGraphic = fill.GetComponent<Image>();
            slider.interactable = false;
            slider.minValue = 0;
            slider.maxValue = 100;
            slider.value = 100;
            return slider;
        }

        private static void SetAnchors(RectTransform rt, Vector2 min, Vector2 max)
        {
            rt.anchorMin = min;
            rt.anchorMax = max;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
        }

        private static void CreateWorldLighting()
        {
            var light = new GameObject("Directional Light").AddComponent<Light>();
            light.type = LightType.Directional;
            light.intensity = 1.1f;
            light.transform.rotation = Quaternion.Euler(48f, -35f, 0f);
        }

        private static Material CreateColorMaterial(string name, Color color)
        {
            string path = GeneratedFolder + "/" + name + ".mat";
            var existing = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (existing)
            {
                existing.color = color;
                EditorUtility.SetDirty(existing);
                return existing;
            }

            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            var mat = new Material(shader) { color = color };
            AssetDatabase.CreateAsset(mat, path);
            return mat;
        }

        private static void EnsureFolder(string parent, string child)
        {
            string path = parent + "/" + child;
            if (!AssetDatabase.IsValidFolder(path))
                AssetDatabase.CreateFolder(parent, child);
        }

        private static void BindObject(Object target, string field, Object value)
        {
            var serialized = new SerializedObject(target);
            var property = serialized.FindProperty(field);
            if (property != null)
            {
                property.objectReferenceValue = value;
                serialized.ApplyModifiedPropertiesWithoutUndo();
            }
        }

        private static void BindString(Object target, string field, string value)
        {
            var serialized = new SerializedObject(target);
            var property = serialized.FindProperty(field);
            if (property != null)
            {
                property.stringValue = value;
                serialized.ApplyModifiedPropertiesWithoutUndo();
            }
        }
    }
}
#endif
